//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Orders_Detail = new HashSet<Orders_Detail>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int book_id { get; set; }
        public Nullable<int> cate_id { get; set; }
        public string book_name { get; set; }
        public string book_image { get; set; }
        public Nullable<int> book_price { get; set; }
        public string book_author { get; set; }
        public Nullable<int> book_promotionprice { get; set; }
        public Nullable<int> book_viewcount { get; set; }
        public string book_description { get; set; }
        public string book_detail { get; set; }
        public Nullable<int> book_quantity { get; set; }
        public string book_status { get; set; }
    
        public virtual BookCategory BookCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders_Detail> Orders_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
