//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cart()
        {
            this.Orders_Detail = new HashSet<Orders_Detail>();
        }
    
        public int cart_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> book_id { get; set; }
        public string cart_name_book { get; set; }
        public string cart_image { get; set; }
        public Nullable<int> cart_price { get; set; }
        public Nullable<int> cart_quantity { get; set; }
        public Nullable<int> cart_total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders_Detail> Orders_Detail { get; set; }
    }
}
