//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_Detail
    {
        public int order_id { get; set; }
        public int cart_id { get; set; }
        public Nullable<int> book_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public string voucher { get; set; }
        public Nullable<int> total { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Cart Cart { get; set; }
        public virtual Order Order { get; set; }
    }
}
