//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Orders_Detail = new HashSet<Orders_Detail>();
        }
    
        public int order_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> order_address { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<int> order_payment { get; set; }
        public string order_status { get; set; }
        public Nullable<System.DateTime> order_deliverydate { get; set; }
        public Nullable<int> order_discount { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders_Detail> Orders_Detail { get; set; }
    }
}
